name:                sudokuSolver
version:             0.1.0.0
github:              "shrimansoft/sudokuSolver"
license:             BSD3
author:              "Shriman"
maintainer:          "shrimansoft@hotmail.com"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shrimansoft/sudokuSolver#readme>

dependencies:
- array
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  sudokuSolver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudokuSolver

tests:
  sudokuSolver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudokuSolver
